version: "3.9"
services:
  database:
    image: postgres:15-alpine
    container_name: qafzah_database
    environment:
      POSTGRES_USER: ${DB_USER}     
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}         # Database name from .env
    ports:
      - "5432:5432"                   # Map the PostgreSQL port to the host
    volumes:
      - database_data:/var/lib/postgresql/data # Persist data between restarts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data:
