version: '3.8'  # Define the Docker Compose version

services:
  db:
    image: mysql:8.0  # Using the MySQL 8.0 image
    container_name: mysql_container  # Set a meaningful container name
    env_file:
      - .env  # Reference your .env file
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Root password from .env
      MYSQL_DATABASE: ${DATABASE_NAME}            # Database name from .env
      MYSQL_USER: trilux                          # Directly set the username
      MYSQL_PASSWORD: trilux                      # Directly set the user password
    ports:
      - "3306:3306"  # Map MySQL's port to your machine
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql_data:  # Volume for MySQL data persistence
